services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: bdmacuin
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bdmacuin
      MYSQL_USER: ejc
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - macuin_network
    ports:
      - "3307:3306"   # Exponiendo el puerto 3307 de tu máquina local al 3306 del contenedor

  # Servicio para Flask
  flask:
    build:
      context: ./flask
    container_name: flask-macuin
    ports:
      - "5010:5000"  # Exponiendo Flask en el puerto 5000
    depends_on:
      - mysql
    networks:
      - macuin_network

  # Servicio para la API
  api:
    build:
      context: ./api
    container_name: api-macuin
    ports:
      - "5000:5000"  # Exponiendo la API en el puerto 8000
    depends_on:
      - mysql
    networks:
      - macuin_network

  # Servicio para Laravel
  laravel:
    build:
      context: ./laravel
    container_name: laravel-macuin
    ports:
      - "5020:5000"  # Exponiendo Laravel en el puerto 8001
    depends_on:
      - mysql
    networks:
      - macuin_network

# Definir las redes que usarán los contenedores
networks:
  macuin_network:
    driver: bridge

# Volúmenes para persistencia de datos de MySQL
volumes:
  mysql: