services:
  mysql:
    image: mysql:8.0
    container_name: bdmacuin
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bdmacuin
      MYSQL_USER: ejc
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - macuin_network
    ports:
      - "3307:3306"

  flask:
    build:
      context: ./flask  # Apunta a la carpeta flask
    container_name: flask-macuin
    ports:
      - "5010:5000"
    depends_on:
      - mysql
    networks:
      - macuin_network

  api:
    build:
      context: ./api  # Apunta a la carpeta api
    container_name: api-macuin
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - macuin_network

  laravel:
    build:
      context: ./laravel  # Apunta a la carpeta laravel
    container_name: laravel-macuin
    ports:
      - "5020:5000"
    depends_on:
      - mysql
    networks:
      - macuin_network

networks:
  macuin_network:
    driver: bridge

volumes:
  mysql: